### ISSUE TITLE
Allow KVMTOOL Guest/VM to use RISC-V V-Extension

### ISSUE THREAD

**Issue by avpatel** [kvm-riscv/linux#23]
When the host supports RISC-V V-Extension, the KVMTOOL should:
1. Append "v" to the HART ISA string in generated DTB
2. Dump V-extension state in kvm_cpu__show_registers()

Need RISC-V V-extension virtualization in KVM RISC-V (https://github.com/kvm-riscv/linux/issues/13)
Need KVM ONE_REG interface for accessing Guest VCPU V-extension state (https://github.com/kvm-riscv/linux/issues/14)

Not started yet.

**Comment by xiaobo55x** [comment]
Hi @avpatel,

I'm Haibo, from Intel RISC-V opensource software team.

Recently, we are starting look into the H-extension support in related software stack,
and noticed you guys had already done lots of work. Just wonder do you have a summary
on the current status and plan for the H-extension support? Or any work we can do some help?

Regards,
Haibo

**Comment by avpatel** [comment]
Hi Haibo,

Thanks for your interest, we do have development items where you (or your team) can start contributing.

Can you start an email thread with
Me: apatel [at] ventanamicro [dot] com
Drew: ajones [at] ventanamicro [dot] com
Atish: atishp [at] rivosinc [dot] com
?

Maybe we can have a meeting with your team if more folks are interested in contributing?

Regards,
Anup
