### ISSUE TITLE
htval is allowed to be written to zero, kvm may not be able to use this register

### ISSUE THREAD

**Issue by francis4096** [kvm-riscv/linux#30]
https://github.com/kvm-riscv/linux/blob/ad56588f06e1b93c9a85006044fb7e780d9049a1/arch/riscv/kvm/vcpu_exit.c#L429

Form riscv-privilegaed document section 5.2.7, htval is allowed to be written to zero, so kvm software may not be able to use this register. 
`When a guest-page-fault trap is taken into HS-mode, htval is written with either zero or the guest physical address that faulted, shifted right by 2 bits. `

**Comment by avpatel** [comment]
HTVAL needs to have guest physical address for good performance on KVM, Xvisor, and lot of other hypervisors. At the moment, these hypervisors will simply fail and kill the Guest/VM if HTVAL is zero.

This means HTVAL being non-zero is kind of mandated from software stand point.

Regards,
Anup

**Comment by DizhaoWei** [comment]
Hi, as you said, whether the HTVAL must be exact faulted guest physical address (GPA)? If so, each entry of uTLB/MMU must maintain the PTE.ppn (for MPA) and the GPA, it is very not friendly for hardware implementation, is right?

**Comment by avpatel** [comment]
The decision of depending on HTVAL is purely for realistic performance of KVM and other hypervisors.

If there is more demand for supporting HTVAL hardwired to zero then we can incrementally add this feature to KVM and Xvisor.

Regards,
Anup

**Comment by DizhaoWei** [comment]
Thanks for your reply!

I wonder that how much impact does the HTVAL hardwired to zero have on performance of hypervisor, is there any quantitative data?

**Comment by avpatel** [comment]
The impact is big (don't have exact numbers) because HTVAL is accessed in performance critical path of most hypervisors which deals with dynamically map/unmap guest RAM pages and emulating guest MMIO (interrupt controller, VirtIO, etc).

Regards,
Anup
