### ISSUE TITLE
The value of MISA CSR is 0x800000000014112d, not support H extension?

### ISSUE THREAD

**Issue by GToad** [kvm-riscv/linux#31]
Sorry, but I read the value of MISA and it is 0x800000000014112d.
the 8th bit (bit[7]) is 0, so this means this version does not support H extension for hypervisor? 
Thank you for help!

**Comment by avpatel** [comment]
Yes, the H-extension bit in MISA should be set for hypervisor extension to be available.

Regards,
Anup

**Comment by GToad** [comment]
> Yes, the H-extension bit in MISA should be set for hypervisor extension to be available.
> 
> Regards,
> Anup

Thank you so much! 
But I follow this doc [https://github.com/kvm-riscv/howto/wiki/KVM-RISCV64-on-QEMU] and use the qemu [https://github.com/kvm-riscv/qemu]. The MISA of it is still  0x800000000014112d. Is that means the KVM-RISCV64 can run VMs even without H extension?

**Comment by avpatel** [comment]
MISA will only be checked by OpenSBI whereas Linux will check ISA string in DT for H-extension.

If you remove "x-h=true" from QEMU command line then Linux will boot but KVM will not be available.

Regards,
Anup

**Comment by GToad** [comment]
> MISA will only be checked by OpenSBI whereas Linux will check ISA string in DT for H-extension.
> 
> If you remove "x-h=true" from QEMU command line then Linux will boot but KVM will not be available.
> 
> Regards,
> Anup

Thank you very much! I run it without "x-h=true" !
Thank you! Now the MISA is 0x80000000001411ad, H extension is available.
