### ISSUE TITLE
Allow QEMU Guest/VM to use in-kernel AIA support

### ISSUE THREAD

**Issue by avpatel** [kvm-riscv/linux#40]
When the host supports RISC-V AIA, the KVM kernel module will provide in-kernel AIA virtualization and the QEMU should:

1. Detect and configure in-kernel AIA support
2. Generate AIA DT nodes instead of PLIC DT node

Need in-kernel AIA virtualization in KVM RISC-V (https://github.com/kvm-riscv/linux/issues/39)

Not started yet.

**Comment by c0x0o** [comment]
I would like to help if in-kernel AIA support is ready for a basic testing

**Comment by avpatel** [comment]
You can try riscv_kvm_aia_v1 branch of https://github.com/avpatel/linux

The corresponding KVMTOOL changes are in riscv_aia_v1 branch of https://github.com/avpatel/kvmtool

I will be sending out these patches once AIA spec is in public review (probably next 1-2 months).
